### ISSUE TITLE
Process occurence Data, download data, odd format

### ISSUE THREAD

**Issue by ValentinChCloud** [wallaceEcoMod/wallace#120]
Hello,
I got really curious csv format from the component 2 "Process occurence Data"with somes carriage return in the last colunm named "pop".

 # How do I get that
Rstudio
Wallace:
1 Occ Data ->Query database ->Database Gbif -> specie : "Sepia officinalis"->Query database

2 Process Occs ->Select Occurrences On Map ->Draw as I can a beautiful polygon-> Select occurences->Download

# How does it look
Please use this [Galaxy link](https://openstack-192-168-100-44.genouest.org/u/adminsys/h/wallace) to donwload it if needed

```
root@2492b0c03785:/var/log/shiny-server# head _processed_occs.csv
"name","longitude","latitude","year","institutionCode","country","stateProvince","locality","elevation","basisOfRecord","occID","pop"
"Sepia officinalis",-5.607512,36.005236,2017,"iNaturalist","Spain",NA,NA,NA,"HUMAN_OBSERVATION","2","<strong>occID: 2</strong>
<br/>
<strong>Latitude: 36.01</strong>
<strong>Longitude: -5.61</strong>"
"Sepia officinalis",-9.21444,38.4033,2017,"Diveboard","Portugal",NA,"River Gurara Popa",0,"HUMAN_OBSERVATION","3","<strong>occID: 3</strong>
<br/>
<strong>Latitude: 38.4</strong>
<strong>Longitude: -9.21</strong>"
"Sepia officinalis",-5.60726,36.005005,2017,"iNaturalist","Spain",NA,NA,NA,"HUMAN_OBSERVATION","5","<strong>occID: 5</strong>
```
As you can see the last value of each row looks like
```
"<strong>occID: 2</strong>
<br/>
<strong>Latitude: 36.01</strong>
<strong>Longitude: -5.61</strong>"
```

As you can see there is some carriage return betwen each html html tag ( by the way, is it suppose to be?). I don't think it's recommended to have kind of syntax in csv format but it will work with libreoffice for example, but on our side It is a bit problematic ^^"

**Comment by ndimhypervol** [comment]
This column is used for the pop-up info for each point on the leaflet map. That’s why you see the carriage returns (<br>). However, it is not meant to be included in the csv download, so thanks for catching this. In earlier versions it hadn’t been there, so wondering how it got included. I’ll fix this and include in the next CRAN update.

**Comment by ndimhypervol** [comment]
Resolved in multiSp branch.
