### ISSUE TITLE
Being able to upload environmental layers as single multiband tif (suggested enhancement)

### ISSUE THREAD

**Issue by Pakillo** [wallaceEcoMod/wallace#122]
Hi,

First of all, many thanks for wallace. We're trying it and so far it's just great.

As a potential enhancement for the future, I'd like to suggest the ability to upload several environmental layers (user-specified, step 3) all in a single (multiband) tif file. This would be more convenient than having to save and upload each environmental layer one by one (usually there are quite a few).

From the module guidance I first understood that uploading a multiband file would be possible as long as all layers were stored in a single file (e.g. a multiband tif). But when I tried I got an error ("Error in names<-: incorrect number of layer names"), so I understand that's still not possible. Maybe the documentation could clarify this point (for a few minutes I was confused if this was a bug).

I haven't looked into wallace source code but the underlying raster package can read multiband tifs as raster stacks straightforward, so I was hoping implementing this would not be too difficult.

Anyway, feel free to ignore this comment if it doesn't fit into your development plans for Wallace. We can always make it work uploading individual rasters.

Thanks again, and best wishes

Paco

**Comment by Pakillo** [comment]
Sorry, I now see you can select several tif files to upload at once, so that's quite convenient! The only thing we might avoid then is having to store all layers as separate files. But that's a very minor inconvenience. No problem at all!
Thanks again

**Comment by ndimhypervol** [comment]
Thanks for using Wallace! Yes, enabling multi-band rasters should be easy, and I’ll give it a shot in the next version. I’ll also take a second look at the guidance text and see if I can’t make it any more clear. Thanks for the input, and please let us know about anything else that comes up.
