### ISSUE TITLE
Issue with positive and negative bounds. 30'' Worldclim.

### ISSUE THREAD

**Issue by gepinillab** [wallaceEcoMod/wallace#125]
In the current version, there is a problem when the northbound is positive and the southbound is negative. Tracking in the code, I found that the mapCenter function only works when both bounds had the same signs.

I noticed this problem when I downloaded the 30'' worldclim based on species records that are found in the north and the south of the equator.  The extent in the envdata had only negative latitude, so all the records with positive latitude were deleted.

**Comment by gepinillab** [comment]
The problem is not in the mapCenter function, is in how raster::getData download the data. In this particular case, you can only download blocks of 30 grades x 30 grades.

**Comment by ndimhypervol** [comment]
So, is this issue still open, or does the commit fix it? If it doesn't, is this something we can fix?

**Comment by gepinillab** [comment]
Hi @ndimhypervol,

This problem is related with the tiles issue of 30 arcsec. The problem is mentioned in the IMPLEMENTATION section of the Module Guidance.
