### ISSUE TITLE
RM increments: slide bar only sets to whole numbers, and with Hinge RM=0, will not run

### ISSUE THREAD

**Issue by smeenan** [wallaceEcoMod/wallace#130]
These is a two-part issue. First, it would be nice if the slide bar could be set to increments of 0.5.  Second, Wallace crashes if Hinge is selected and the slide bar includes zero.

**Comment by ndimhypervol** [comment]
Fixed both in 3d15d7af2ee0a6bc8c84343720e2f8c891ce3018. Now slider min is 0.5, and it slides to increments of 0.5.
