### ISSUE TITLE
Wallace will not use WorldClim variables specified (30'')

### ISSUE THREAD

**Issue by CarlosRodVaz** [wallaceEcoMod/wallace#136]
Hello all,
I am having an issue in the WorldClim module when I specify the variables to use in the analysis. Regardless of what BioClim variables I select when I load them all 19 variables are loaded. Am I the only one having this bug?

**Comment by gepinillab** [comment]
Dear @CarlosRodVaz,

I apologized for the late reply. I would like to know if you are still having this problem.

Best,
Gonzalo

**Comment by CarlosRodVaz** [comment]
Dear @gepinillab,

No worries! Yes I still have this problem. 

Best,
Carlos

**Comment by gepinillab** [comment]
Gracias Carlos!

You found a bug for rasters with a 30 sec resolution. I will fix this problem in the dev version in Github as soon as possible. Also, this problem will be fixed in the next release on CRAN (v.1.0.6; it will be ready in one month).

Best,
Gonzalo

**Comment by gepinillab** [comment]
Carlos, please let me know if the issue was fixed in the GitHub version of Wallace. You can install it by the following code:
```r
install.packages("devtools")
devtools::install_github("wallaceEcoMod/wallace")
````
