### ISSUE TITLE
update java download link in rJava instructions in the readme file

### ISSUE THREAD

**Issue by meblair** [wallaceEcoMod/wallace#141]
in the readme file re: help on rJava, the link to download java is just for a java update - it might be useful to include a link to download java from scratch (for users that do not have it at all).  this came up for several of the folks in our workshop.

**Comment by gepinillab** [comment]
The original link to download java install the newest version of Java, it is not just an update. The addition of the instructions in the README file could help the users that are installing java for the first time.

**Comment by gepinillab** [comment]
Fixed in #153
