### ISSUE TITLE
process occurrences - prob. w mcp + buffer

### ISSUE THREAD

**Issue by meblair** [wallaceEcoMod/wallace#142]
Gonzalo used the mcp + buffer option for polar bears and two points were conspicuously left out of the polygon!  very odd. He can recreate the issue to demonstrate.

**Comment by gepinillab** [comment]
Resolved in https://github.com/wallaceEcoMod/wallace/commit/9eaaa14a8291f2c574ac7cd3a5e9271e22d74fe5
