### ISSUE TITLE
Error in downloading Session Code for Module 4 onwards

### ISSUE THREAD

**Issue by shirleyxchen** [wallaceEcoMod/wallace#144]
I'm having trouble downloading my Session Code in any format after processing environmental data in Module 4. 

Steps to Reproduce: 

1. Obtain occurrence points in Module 1 from GBIF (n = 100, _Rhinolophus affinis_)
2. Process occurrence data in Module 2 using Spatial Thin (distance = 11 km)
3. Obtain environmental data in Module 3 selecting WorldClim Bioclims (bio1 and bio2, 5 min resolution)
4. Process environmental data in Module 4 using 0.5 degree point buffers with 1000 background points

Session code from 1-3 are downloading fine. After step 4, attempts to download give me a "Failed - Server problem" error and the error in the console gives me the following:
```Warning in file(con, "r") :
  cannot open file 'Rmd/userReport.Rmd': No such file or directory
```

System info:
RStudio 1.1.453 on Windows, R version 3.5.1

**Comment by mlammens** [comment]
Hi @shirleyxchen - just to be clear, you are only completing components 1-4, then going to the last tab to download the Rmd? Is that correct?

**Comment by shirleyxchen** [comment]
I initially discovered the issue when I attempted to download the Rmd after completing all the modules. Module 4 is where the Rmd download stops working - doesn't work for any of the modules afterwards.

**Comment by ndimhypervol** [comment]
@shirleyxchen, very strange -- I cannot reproduce this error. Just ran this on v1.0.5 with your exact specifications, and was able to download the session code after partitioning in the Partition Occs component. Can you confirm that you're using `wallace` v1.0.5?

**Comment by shirleyxchen** [comment]
@ndimhypervol yes, using `wallace` v1.0.5. I'm on a Windows x64 machine. We just ran the same steps on a Mac and encountered the same error (also `wallace` v.1.0.5).

**Comment by ndimhypervol** [comment]
Thanks for that, @shirleyxchen. I just tried this on a different Mac at the lab and had no issues. Let's try to get to the bottom of this. Hey @mlammens, can you try to reproduce this?

**Comment by shirleyxchen** [comment]
@ndimhypervol tried it again and it now seems to be working again!

**Comment by ndimhypervol** [comment]
Thanks, @shirleyxchen! Glad it works now, but any idea what gave you the initial errors? WOuld be good to know for troubleshooting advice in the future.

**Comment by shirleyxchen** [comment]
Hi @ndimhypervol, thanks for checking. 

I don't think this is related to @noamross PR but when I set n=1000 instead of n=100 as the maximum number of occurrence points in Module 1, that _all records_ are removed during Module 3 when loading environmental variables (all 19 bioclim, at a resolution of 30 arc seconds) with this message (nothing in the console): 
`! WARNING : Removed records without environmental values with occIDs: 3, 13, 20, 21, 28, 30, 31, 36, 37, 39, 40, 41, 42, 43, 47, 48, 53, 70, 116, 120, 170, 172, 178, 186, 189, 202, 204, 219, 226, 236, 241, 245, 247, 250, 263, 267, 269, 278, 279, 292, 294, 301, 316, 336, 437, 443, 458, 512, 523, 535, 555, 556, 559, 570, 602, 603, 606, 611, 612, 641, 697, 718, 744, 874, 880, 944, 966`

However, when I set n=100 as the maximum number of occurrences in Module 1, only one occurrence point is removed and I'm able to proceed. 

In both cases I'm still unable to download the environmental mask with a 'No File' error.

**Comment by shirleyxchen** [comment]
@noamross I’ve done that’s but no error messages are appearing in the console.

**Comment by ndimhypervol** [comment]
@shirleyxchen I am not getting the same error. I followed your methodology with

**Comment by ndimhypervol** [comment]
Just thought of something. If you did not input the 30 arcsec rasters and instead downloaded them, `raster` only lets you download tiles and not the whole globe at once, so perhaps you are losing points that fall outside the tile? It shouldn't remove everything though.
