### ISSUE TITLE
Data downloads failing for Modules 1 and 4 

### ISSUE THREAD

**Issue by shirleyxchen** [wallaceEcoMod/wallace#145]
I'm unable to download database occurrence localities in Module 1, or predictor rasters masked to background extent in Module 4 (in any format). 

Steps to Reproduce:

1. Obtain occurrence points in Module 1 from GBIF (n = 100, Rhinolophus affinis). 
Gives download error "dlDbOccs Failed - Server problem" and in the console: `Warning: Error in write.table: unimplemented type 'list' in 'EncodeElement' [No stack trace available]`

2. Process occurrence data in Module 2 using Spatial Thin (distance = 11 km)
Download OK
3. Obtain environmental data in Module 3 selecting WorldClim Bioclims (bio1 and bio2, 5 min resolution)
Download OK
4. Process environmental data in Module 4 using 0.5 degree point buffers with 1000 background points.
Gives download error "dlMsksEnv Failed - No file". No message in console.

System info:
RStudio 1.1.453 on Windows, R version 3.5.1

**Comment by ndimhypervol** [comment]
I can reproduce this, and I found what I think is a bug with the `spocc::occ()` data table not being able to be written to file by `write.csv()`. I posted an issue in the `spocc` repo.
https://github.com/ropensci/spocc/issues/192
Will update when I get more info. Thanks for this notice, @shirleyxchen!

**Comment by noamross** [comment]
@ndimhypervol Given the response over at `spocc`,what do you think of adding a `write_csv_robust()` to `wallace` that would check for list-columns before calling `write.csv`?  A reasonable default that would capture all the information would be to convert any list column to a character column with the JSON representation of the list objects (a common technique for nested data in SQL). Would be happy to write a PR to do this if it makes sense to you.

**Comment by ndimhypervol** [comment]
@noamross Yes, that would be much appreciated! Not sure we need to go so far as to convert the networkkeys list of lists -- for our purposes, we could just detect it and delete it, as @sckott suggested. I can't think of an application for this list in *Wallace*.

**Comment by sckott** [comment]
note that the possibility of a list inside a data.frame for `occ` isn't just for `networkKeys` - could be any field in theory, just to take into account .

**Comment by ndimhypervol** [comment]
Thanks for the tip, @sckott. And thanks to @noamross, the `write.csv()` functionality was fixed with a brand new function, `write_csv_robust()`, that handles the list-of-list fields expertly. @shirleyxchen, can you try the new version (by installing from Github), and report back please? Thanks!

**Comment by shirleyxchen** [comment]
@sckott yes, that's solved the issue. Thanks @noamross!

**Comment by ndimhypervol** [comment]
Excellent! Thanks again @sckott and @noamross.
