### ISSUE TITLE
points not removed from map after Obtain Envs

### ISSUE THREAD

**Issue by ndimhypervol** [wallaceEcoMod/wallace#149]
In component Obtain Envs, if points have NA values for environmental rasters and are automatically removed, they do not disappear from the map when you go to the next component to delineate the background extent.

**Comment by gepinillab** [comment]
Resolved in https://github.com/wallaceEcoMod/wallace/commit/9eaaa14a8291f2c574ac7cd3a5e9271e22d74fe5
