### ISSUE TITLE
Wallace doesn't remove all the duplicates 

### ISSUE THREAD

**Issue by Valengsb** [wallaceEcoMod/wallace#164]
I noticed that Wallace isn't removing all the duplicates within datasets downloaded from databases (GBIF, VertNet). 

In case you want to reproduce the problem, I was working with a dataset of _Didelphis marsupialis_ downloaded from GBIF (I downloaded all the records). It has three records with coordinates 0-0, and those records were plotted on the map even when the "log window" stated that all the duplicates had been removed. 

Using the same dataset, I realize that Wallace just remove the coordinates that are exactly the same so when we have something like [-103.2, 20.**3**] and [-103.2, 20.**289**] Wallace doesn't consider them as duplicates. It would be helpful if you specify that on the guidance.

**Comment by gepinillab** [comment]
Thanks @Valengsb ,

The first example that you mentioned is the same case as the second one. The difference in the coordinates is in other decimal positions that Wallace is not showing in the GUI.

In future versions, we will add options to handle or delete these "duplicates".

**Comment by Valengsb** [comment]
Hi! 
As a friendly reminder, we have to specify in the Guidance the fact that Wallace just removes EXACT duplicates.
