### ISSUE TITLE
Problems with R Markdown: Maxent models 

### ISSUE THREAD

**Issue by Valengsb** [wallaceEcoMod/wallace#170]
R reported the following error/warning when I try to run the line (R Markdown) for build a model with Maxnet:

![image](https://user-images.githubusercontent.com/42625371/46261165-b2a7bb00-c4bd-11e8-8c97-73f1022e70d8.png)

This problem doesn't appear when I build models using BIOCLIM.

**Comment by gepinillab** [comment]
Valen,

Please, can you send me the RMD files to reproduce the issues (via e-mail)?

Thanks,
Gonzalo

**Comment by gepinillab** [comment]
Valen,

I didn't reproduce this issue using you Markdown. Can you re-run the analysis again and let me know if you are having the same problem?

Thanks,
Gonzalo

**Comment by gepinillab** [comment]
Hi,

Can you check if you are getting the same problem in another machine? I am not having problems in mine.

Thanks,
Gonzalo

**Comment by Valengsb** [comment]
Hi!

I have to finish something here but then I'll check that. 

Valen

**Comment by Valengsb** [comment]
Hi!

Today I couldn’t work on Wallace but tomorrow after the Nasa meeting I’ll work on that. 

Valen.

**Comment by Valengsb** [comment]
Hi! 

After downloading the last update of Wallace, I don't have that problem in my mac anymore. However, I tried to run the RMD on another computer (windows) and I got the following problem:

![image](https://user-images.githubusercontent.com/42625371/46485381-3238d100-c7c1-11e8-94d8-aba8b9f31e12.png)
Since you don't get that problem on your computer, maybe it is a problem of that particular machine. However, I'll send you the RMD with which I got the problem in the windows pc in case you want to check it again

**Comment by gepinillab** [comment]
Valen,

Can you check if the other machine has installed the last version of ENMeval (=0.3.0)?

Gonzalo

------------------------------------------------------------------------------------------
Gonzalo E. Pinilla Buitrago
PhD Student | City University of New York
M.Sc. | Instituto de Ecología A.C., MX
B.Sc. Biology | Universidad Nacional de Colombia
+1 (212) 650-8424 | @chalo_pinilla

________________________________

**Comment by Valengsb** [comment]
Yes, I just installed all the packages.
