### ISSUE TITLE
Draw polygon tool enhancement

### ISSUE THREAD

**Issue by Valengsb** [wallaceEcoMod/wallace#174]
When using the Draw polygon tool, it would be useful if the cross used to draw shows the coordinates (log, lat) of the point where it is on the map.  

![image](https://user-images.githubusercontent.com/42625371/46431297-6ce72e80-c719-11e8-9e1d-b5f80fc1ea2a.png)

It will be even more useful in the **Project component** since there isn’t an option to load a shape file for the region where the users will project.

**Comment by gepinillab** [comment]
Available in multiSp
