### ISSUE TITLE
Obtain Occurrence Data component - Download option 

### ISSUE THREAD

**Issue by Valengsb** [wallaceEcoMod/wallace#177]
The download option should have the option to download the edited table as described in the _log window_ (i.e., without records lacking coordinates and duplicates). Currently, Wallace only downloads the table as it is downloaded from the databases.

**Comment by Valengsb** [comment]
I checked if the Multisp version already has this option but it doesn't. Moreover, I couldn't download the raw occurrence data. When I try to do that, I get the following error:
![image](https://user-images.githubusercontent.com/42625371/47683096-e81af380-dba4-11e8-8aed-a0612174c38a.png)

**Comment by gepinillab** [comment]
Available in multiSp
