### ISSUE TITLE
Project Model - Download layers

### ISSUE THREAD

**Issue by Valengsb** [wallaceEcoMod/wallace#183]
Wallace has to re-download the layers each time that the user makes a projection in the same session. For example, if the users project using any of the three prediction outputs and then they change the output and project again, Wallace has to download the layers each time. Isn’t there any space in the user computer where Wallace saves the files that are downloaded?

**Comment by ndimhypervol** [comment]
confirm

**Comment by Valengsb** [comment]
Jamie was right, Wallace already does this.

**Comment by gepinillab** [comment]
@Valengsb Can I close this issue?

**Comment by Valengsb** [comment]
Yep!
