### ISSUE TITLE
.png and .pdf images 

### ISSUE THREAD

**Issue by Valengsb** [wallaceEcoMod/wallace#185]
The image shown is a .pdf raw prediction downloaded from Wallace.  

![image](https://user-images.githubusercontent.com/42625371/46484423-64493380-c7bf-11e8-85db-36f794408bdb.png)

Consider:
1.  keeping the same color gradient as shown in Wallace
2. Adding a legend (color gradient values)
3. Describing better the axes (i.e., log and lat) or remove those "x", "y" labels, they are unnecessary. 

Every image (model outputs, projections, environmental similarity) downloaded as .png or .pdf are in the same format.

Additionally, PNGs have a very weird distortion of the Earth!!
![image](https://user-images.githubusercontent.com/42625371/48098304-50438800-e1ea-11e8-8dcc-8983dece64f7.png)

**Comment by gepinillab** [comment]
Just fixed for PNG

**Comment by gepinillab** [comment]
Available in multiSp
