### ISSUE TITLE
ui text for user-specified study extent poly should include .shp

### ISSUE THREAD

**Issue by ndimhypervol** [wallaceEcoMod/wallace#190]
The current ui text for this module just specifies the .csv option, although .shp files are also allowed. The guidance text reflects this, but the ui text should also.

**Comment by Valengsb** [comment]
Just to have in mind, we also have to write the guidance for the new modules, which are:

- Obtain Occurrence Data - Module guidance 
  * Query Database (Present)
  * Query Database (Paleo)

- Environmental Space - Component and module guidance
  * Principal Components Analysis
  * Occurrence Density Grid
  * Niche Overlap

**Comment by gepinillab** [comment]
Available in multiSp
