### ISSUE TITLE
[multiSp] add download option in the Visualize component 

### ISSUE THREAD

**Issue by gepinillab** [wallaceEcoMod/wallace#194]

**Comment by Valengsb** [comment]
The following components also lack the download option: 
 - Process Occurrence Data 
 - Partition Occurrence Data

**Comment by Valengsb** [comment]
In the Visualize component, the modules that lack download options are:
- Plot Response Curves
- Map Prediction

**Comment by gepinillab** [comment]
@ndimhypervol 
Hi Jamie, we need to define the options to download in the environmental space component.
