### ISSUE TITLE
ERROR: dependencies ‘rgdal’, ‘XML’

### ISSUE THREAD

**Issue by isaacovercast** [wallaceEcoMod/wallace#197]
Mac OS 10.14
R 3.5.1
Rstudio 1.1.456

Clean install on Mac OS, after calling `install.packages('wallace')`

```
ERROR: dependencies ‘rgdal’, ‘XML’ are not available for package ‘wallace’
* removing ‘/Users/isaac/miniconda2/lib/R/library/wallace’
Warning in install.packages :
  installation of package ‘wallace’ had non-zero exit status
```

`conda install -c conda-forge r-rgdal` Fixed the `rgal` issue. &&

`conda install r-xml` fixed the XML requirement. Not sure why conda did a better job here than cran, but it fixed it for me.

**Comment by isaacovercast** [comment]
Some combination of these conda install commands followed by a `install.packages("wallace")` in rstudio brought me to a place where it's working now. This is probably only useful info for people who use conda, but thought I'd document it for posterity....
```
sudo open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg
conda install -c r r-base=3.5.1 rstudio
conda install -c conda-forge libgdal
conda install  r-xml
conda install  r-leaflet
conda install  r-spacc
```

**Comment by isaacovercast** [comment]
Also, when loading env data as .tiff it was failing and I was getting:
```
Warning: Error in .rasterObjectFromFile: Cannot create RasterLayer object from this file; perhaps you need to install rgdal first
  101: stop
  100: .rasterObjectFromFile
   99: brick
   97: .quickStackOneFile
   96: .local
   95: raster::stack
   90: <reactive> [modules/mod_c3_userEnvs.R#24]
   74: userEnvs
   73: observeEventHandler [/Users/isaac/miniconda3/lib/R/library/wallace/shiny/server.R#349]
    2: shiny::runApp
    1: run_wallace
```
Even though `r-rgdal` was installed, but turns out you also need `gdal` installed since r-rgdal is just a wrapper, so also need to run `conda instal -c conda-forge gdal ncurses` and now env data imports just fine.

Sorry to spam this issue, but figure i'd add running commentary of things i needed to do to get it working, in case somebody in the future has this issue it'll be more googleable.

**Comment by isaacovercast** [comment]
Step 6 (Model): Maxent
select algorithm: maxnet
feature classes: :L/LQ
regularization: defaults
```
Warning in dismo::randomPoints(bgMask, input$bgPtsNum) :
  generated random points = 0.3382 times requested number
*** Running ENMevaluate using maxnet v.0.1.2 ***
Doing user-defined evaluation groups...
Warning: Error in dyn.load: unable to load shared object '/Users/isaac/miniconda3/lib/R/library/Matrix/libs/Matrix.so':
  dlopen(/Users/isaac/miniconda3/lib/R/library/Matrix/libs/Matrix.so, 6): Library not loaded: @rpath/R/lib/libRlapack.dylib
  Referenced from: /Users/isaac/miniconda3/lib/R/library/Matrix/libs/Matrix.so
  Reason: image not found
  104: <Anonymous>
```
Install lapack and copy the dylib to the right place:
```
conda install -c conda-forge lapack
cp pkgs/r-base-3.5.1-h539fb6c_1/lib/R/lib/libRlapack.dylib lib/R/lib/`
```
Since the Matrix library was giving the error a simple load of this library to test the lapack fix gives a new error:
```
R
> library(Matrix)
Error: package or namespace load failed for ‘Matrix’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/isaac/miniconda3/lib/R/library/Matrix/libs/Matrix.so':
  dlopen(/Users/isaac/miniconda3/lib/R/library/Matrix/libs/Matrix.so, 6): Symbol not found: _libintl_dgettext
  Referenced from: /Users/isaac/miniconda3/lib/R/library/Matrix/libs/Matrix.so
  Expected in: /Users/isaac/miniconda3/lib/R/lib/libR.dylib
 in /Users/isaac/miniconda3/lib/R/library/Matrix/libs/Matrix.so
```
This is a missing gettext symbol, so:
```
conda install -c conda-forge gettext
# Must reinstall Matrix.so now
conda install -c conda-forge r-matrix -f

R
> library(Matrix)
>
```
Fixed.

**Comment by isaacovercast** [comment]
After this I got a weird error running the Maxent model again:
```
 internal error -3 in R_decompress1
Warning: Error in get: lazy-load database '/Users/isaac/miniconda3/lib/R/library/Matrix/R/Matrix.rdb' is corrupt
```
Turns out this is just a result of needing to restart R, so I restarted R and it worked.

**Comment by isaacovercast** [comment]
THis is more of a dependency hell issue than a wallace issue, so i'll close it. It could be nice to distribute a docker image to avoid this.

Wallace is super cool guys!

**Comment by gepinillab** [comment]
Isaac,

Thanks for your documentation. I just the title to make it more "informative". Feel free to edit it again.

Best,
Gonzalo
