### ISSUE TITLE
Support for run_wallace() on headless servers

### ISSUE THREAD

**Issue by isaacovercast** [wallaceEcoMod/wallace#198]
Hi folks,

I'm running wallace on a headless workstation and using an ssh tunnel to talk to the wallace instance from my laptop. 2 little requests would make this better and probably wouldn't have noticeable effect for others:

1) Every time you run a new R instance it looks like Wallace samples a new random port number within some narrow range in the 6000-7000 area. It would be nice if it just picked a specific port number, and then only changed if this port was not available. (This is similar to how jupyter notebooks work, it has a default in the unallocated port space, and then picks a new one if that port is busy, very convenient for remote work).

An alternate solution would be to add a flag to run_wallace() to specify the port to run on. Just as good.

2) Adding a flag to not launch browser. Similar, launching a browser process on a headless server is unnecessary, and I see that inside run_wallace there is a call to `launch.browser = TRUE`. If there could be an argument to run_wallace() to control this behavior (with the default behavior being TRUE), then this would be convenient as well.

Thanks!!!

**Comment by gepinillab** [comment]
Thanks again! You pull is now on the master branch!
