### ISSUE TITLE
Download folder

### ISSUE THREAD

**Issue by Valengsb** [wallaceEcoMod/wallace#205]
**Rob:** There is no option to decide where to save the files that are downloaded. Wallace saves them on downloads. Consider adding that option. 

**Valen:** 
1. Could Wallace create a folder (within the R directory that is being used) each time that I run it and save the files that are downloaded in that folder? 
2. I know that Wallace downloads the Worldclim layers but where does it save them? Maybe it could save the files that are downloaded in that folder.

**Comment by ndimhypervol** [comment]
I am pretty sure this is either a browser or Windows option. _Wallace_ does not decide where to download files to. It depends on the native options of the browser/OS. We can add guidance text to inform users about where downloaded files go.
