### ISSUE TITLE
wallace software freezes

### ISSUE THREAD

**Issue by Rolini82** [wallaceEcoMod/wallace#218]
Bula from Fiji. Currently Iam learning how to use Wallace ( using R studio) but unfortunately it keeps on freezing at step 6 when i run maxent. even no error appears on the rstudio version. kindly requesting for help.

**Comment by ndimhypervol** [comment]
Can you please post the error that appears in the R console? It will help
us diagnose. Thanks!

Jamie

**Comment by Rolini82** [comment]
Hello
 Thank for your reply.
Actually im using rstudio and noting error message appear on the software
when wallace freezes.

I would like to known what the speed at which wallace perform best.

I did speed test of the network here at time its as low as 0.55mb. I think
its very slow. May be that the reason why its freeze at step 6 maxent..

Looking forward to hearing from you.

Thanks
Rolini

**Comment by ndimhypervol** [comment]
That is strange. I am guessing this is a Maxent problem. Have you had
success running models with BIOCLIM or maxnet? You need to download Maxent
and put maxent.jar into the correct directory in the dismo/jar folder (type
?dismo::maxent into R for detailed info). Please make sure you've done
that. Further, you need to make sure that library(rJava) works on your
computer. If not, we have some troubleshooting steps on the Wallace Github
page.

Jamie

**Comment by gepinillab** [comment]
Dear Rolini82,

Feel free to open the issue again if you consider it.

Best,
Gonzalo
