### ISSUE TITLE
GBIF DOI

### ISSUE THREAD

**Issue by Valengsb** [wallaceEcoMod/wallace#221]
Since GBIF requests to be cited when its data is used, Wallace should generate the DOI when downloading GBIF data.

**Comment by rsh249** [comment]
GBIF does not assign doi numbers to downloads through their RESTful JSON API. This is what all the rOpenSci packages use so also how most R users access GBIF. The difficulty in doi numbers is on GBIFs end. Not a feature of any independent packages.

**Comment by gepinillab** [comment]
Hi @Valengsb and @rsh249,

Thanks for the ['occCite'](https://github.com/hannahlowens/occCite) package that @hannahlowens is developing. The upcoming version (v2) of Wallace will have the option to get the DOI in the windows log. 

https://github.com/wallaceEcoMod/wallace/commit/9030bfe6eb7bb3cef4e9cd59bc17d6a264c486db

Best,
Gonzalo

**Comment by gepinillab** [comment]
Available in multiSp
