### ISSUE TITLE
Models must first be run in component 6 

### ISSUE THREAD

**Issue by xpf7622** [wallaceEcoMod/wallace#226]
After I install wallace, I runned the commnad run_wallace. Then, there is a window prompted in the chrome. at the adress, http://127.0.0.1:3926/, there is a  error as follows, which appears in the seventh TAB: Visualize :

***WELCOME TO WALLACE***
------------------------------------------------------------------------------------
Please find messages for the user in this log window.
------------------------------------------------------------------------------------
! ERROR : Models must first be run in component 6.

**Comment by gepinillab** [comment]
Hi @xpf7622.

Can you give me more information about your issue? I'm not sure if you follow all the steps before component 7. The error msg that you get means that you need to run a model in component 6. Did you have some issue in this component?

Best,
Gonzalo
