### ISSUE TITLE
Bug using user-defined background and spatial partition

### ISSUE THREAD

**Issue by BrunoVilela** [wallaceEcoMod/wallace#237]
Hi guys,
I found a bug when I use a user-defined background shapefile, and the background do not encompass all my points. The error occurs when I am using spatial partitions for the model evaluation. Wallace assigns the groups before removing the NA points in this case, which generates an error at ENMeval::ENMevaluate. I solved this by removing the points that were outside the shapefile after uploading it.
I hope it helps.
Cheers!

**Comment by gepinillab** [comment]
Hi Bruno,

Thanks for letting us know about this issue. In a new drawExtent module (Wallace v2), I tackled this problem by giving an error if the polygon didn't include all the points (I can use the same error for user shapefile). Based on the current workflow, we expect that the points not used in the analysis are deleted in the process occurrences component.

I have two ideas that can fix this problem.
1. Avoid the creation of background extent polygon if this doesn't include all the points. This means that users need to delete these points in the poccs component.
2. Delete all points automatically outside the user-polygon before the partition of the points. Although, I don't like the idea that in the user-shapefile module is deleting, and the drawPolygon is giving an error. I prefer to use the same for both modules.

@ndimhypervol and @BrunoVilela: what do you think about these solutions?
@BrunoVilela, your feedback will always be welcome!

**Comment by ndimhypervol** [comment]
Sorry for the late reply. I think option 1 is ideal, because there are few cases I can imagine where one would want to specify a background extent that excludes some of the occurrence points (unless I am misunderstanding). Throwing an error would alert the user that the points are being excluded, and they would likely fix the polygon.

**Comment by gepinillab** [comment]
Thanks again for reporting this issue @BrunoVilela. Option 1 (print error) will be available in Wallace v2.

Best,
Gonzalo

**Comment by gepinillab** [comment]
Available in multiSp
