### ISSUE TITLE
Please add an options to manually set field separator (comma, tab, semicolom, etc.) for user-specified datasets

### ISSUE THREAD

**Issue by strobilurus** [wallaceEcoMod/wallace#238]
occurence.txt file from the DarwinCore Archive uses tab instead of comma as field separator. When we downloaded a DWCoA for further user-specified processing and then tried to upload it to Wallace as User-specified Occurences, we might encountered an error in "read.table" function.
Warning: Error in read.table: more columns than column names

**Comment by hannahlowens** [comment]
By way of further explanation, the comma delimiter was a problem because we were using Wallace as part of a workshop in the Balkans where in many cases, commas instead of periods are used as decimal indicators. Perhaps this is something that could be fixed with an added argument?

**Comment by gepinillab** [comment]
Hi @strobilurus and @hannahlowens,

Thanks for reporting this bug and the suggestion of how to fix it. I will discuss this with the dev-team. Another solution is giving an error message in the log windows to remind the user that the file needs to use a comma as a separator (Wallace will not crash). Although the option to provide several filed separator is easy to implement. We will let you know once we fix this on the software. In the meantime, R and excel could be an easy way to get a file with comma separators.

Best,
Gonzalo

**Comment by hannahlowens** [comment]
Hi @gepinillab,
Thanks for passing this along to the dev-team!

Excel is actually a big part of the problem. For many of the folks we were working with, who were primarily from Balkan countries, they were running their machines in their native language modes. This means if the .csv is opened in Excel, Excel will automatically change points to commas. Find and replace doesn't work--you end up with a number with multiple points (e.g. "1.032.456"). The real solution is, once any data cleaning has been done in Excel, or however the .csv has been prepared prior to modeling, is to open the file in a text editor that does not have "helpful" native language interpretation functions and then save the file as s UTF-8 .csv file. This is a bit of a pain, hence the request.

Best,
Hannah

**Comment by gepinillab** [comment]
Hi @strobilurus and @hannahlowens,

Upcoming v2 will include an option to define the field and the decimal separator. This will fix your problem with reading tables. Once a beta version is ready, I would like to check if this issue was solved. I will let you know when v2 is ready for testing.

Thanks again for let us know about this bug.

Best,
Gonzalo
