### ISSUE TITLE
Erro ao instalar dependências do wallace

### ISSUE THREAD

**Issue by CarvalhoResearch** [wallaceEcoMod/wallace#263]
I'm trying to install wallace, but to no avail. see:

Warning messages:
1: In install.packages("wallace") :
  installation of package ‘ENMeval’ had non-zero exit status
2: In install.packages("wallace") :
  installation of package ‘rgeos’ had non-zero exit status
3: In install.packages("wallace") :
  installation of package ‘rgdal’ had non-zero exit status
4: In install.packages("wallace") :
  installation of package ‘geoaxe’ had non-zero exit status
5: In install.packages("wallace") :
  installation of package ‘rgbif’ had non-zero exit status
6: In install.packages("wallace") :
  installation of package ‘spocc’ had non-zero exit status
7: In install.packages("wallace") :
  installation of package ‘wallace’ had non-zero exit status
>

**Comment by gepinillab** [comment]
Hi Carlos,

Thanks for reporting this issue. I am not sure about the reason for this issue, but my first guess is that it is not related to Wallace per see. I would like to have more information to help you. Can you answer the following questions?

1. Are you installing Wallace from CRAN or GitHub (using devtools packages)?
2. Are you having the same error when you are installing other packages on R?
3. Which Operative system are you using (macOS, Windows, Linux, etc.)?

Once we get these answers, I think that we can start to figure out your problem.

Best,
Gonzalo

**Comment by CarvalhoResearch** [comment]
Dear Gonzalo,
thank you very much for the return, I apologize for that unanswered time. I tried to install the development version of github, using devtools, but was unsuccessful. I can install other packages, such as rgdal and raster. i'm using linux kubuntu 19.10. 
best, 
Carlos

**Comment by gepinillab** [comment]
No problem Carlos.

Which error did you get when trying to install from github?

Before installing the GitHub version, I suggest updating all the packages. Also, when installing Wallace use TRUE for the dependency parameter.

_install.packages("devtools")
devtools::install_github("wallaceEcoMod/wallace", dependencies = TRUE)_

Let me know if this works for you.

Best,
Gonzalo

**Comment by CarvalhoResearch** [comment]
the result obtained with github was as follows: Installation failed: `there is no package called ‘curl’`. As I have the conda installed I tried a `conda install r-curl ` and managed to install r-curl. so I tried again using devtools and returned the following:` ERROR: dependencies ‘leaflet’, ‘spocc’, ‘ENMeval’, ‘rgeos’, ‘raster’, ‘rgdal’, ‘rgbif’ are not available for package ‘wallace’`

**Comment by gepinillab** [comment]
Hi Carlos,

I am not sure what is going on, but it looks like the dependencies parameters is not working. All package listed in your error are dependencies of Wallace. The quickest solution is installing manually each of the package.

But why do you want to install the github version of Wallace? Right now, CRAN version is technically the same to the one on GitHub.

Best,
Gonzalo

**Comment by CarvalhoResearch** [comment]
I tried to install via CRAN and GitHub, but I get the same problem with the dependencies. I am now trying to install one by one. Thank you

**Comment by gepinillab** [comment]
I am sorry about what is going on. I am not sure if this is a problem with Linux.

Keep in mind that you can use a vector of characters to install several packages at the same time.

_install.packages(c(‘leaflet’, ‘spocc’, ‘ENMeval’, ‘rgeos’, ‘raster’, ‘rgdal’, ‘rgbif’))_

Best,
Gonzalo

**Comment by CarvalhoResearch** [comment]
No need to apologize Gonzalo, I am so grateful for responding so quickly! never before have I received so much attention on github.

**Comment by CarvalhoResearch** [comment]
Dear Gonzalo, 
I finally managed to install the wallace. First I adjusted R 3.6.3 via anaconda, then I installed them all as dependencies one by one. However when using the run_wallace () command I have the following answer: Error in utils :: browseURL (appUrl):
  'browser' must be a non-empty character string. Could you please help me?

Best,
Carlos

**Comment by gepinillab** [comment]
Hi Carlos,

I think you are facing a problem with the configuration of your browser in R. It is an issue that I am not sure how to fix, but I will do my best to help you. Before to continue, I will like to know more information:

1. Are you running Wallace on R or RStudio?
2. Which browser do you have installed on your machine?
3. Did you get more messages or errors in the console? If possible, I will like to know every message that you get in the console once you command run_wallace()?

I am not sure how long it will take us to figure out the problem. But I will be happy to be sure that Wallace is running on any Linux systems.

Best,
Gozalo

**Comment by CarvalhoResearch** [comment]
Hello, I'm running via R, I have chrome and firefox installed, however chrome is the default. After running run_wallace () this is the only problem I get. However I managed to get around using options (browser = "firefox"), this opens the wallace via firefox. I thank you very much for your attention, if you don't mind I think you can close the topic.
Thank you very much for your help and also for the wallace, I find it very intuitive :)
best,
Carlos

**Comment by gepinillab** [comment]
Hi Carlos,

I am glad that you figure out how to fix the problem. I hope that you can use Wallace without problems. If no, let me know if you have another issue.

Best,
Gonzalo
