### ISSUE TITLE
live instance of app?

### ISSUE THREAD

**Issue by trashbirdecology** [wallaceEcoMod/wallace#286]
Is the application hosted somewhere online? If not, consider making that clear on the .io landing page

**Comment by gepinillab** [comment]
Dear Jessica,

Thanks for your suggestion. The only option available now is installing Wallace on a local machine. However, we are planning to host Wallace online in the future. We will make clear the current situation on our website

@mlammens: Would you like to add something else?

Best,
Gonzalo
