### ISSUE TITLE
Close the Tab browser automatically

### ISSUE THREAD

**Issue by gepinillab** [wallaceEcoMod/wallace#296]
Explore the option to add a button in the GUI to close the shiny app and the R console process.

Some links to start:
https://stackoverflow.com/questions/35306295/how-to-stop-running-shiny-app-by-closing-the-browser-window
https://stackoverflow.com/questions/32529215/close-a-shiny-app-on-a-click

**Comment by bjohnso005** [comment]
@gepinillab we can close this, no?

**Comment by gepinillab** [comment]
Yes!
