### ISSUE TITLE
user-spec occ data warning

### ISSUE THREAD

**Issue by bjohnso005** [wallaceEcoMod/wallace#336]
In the User-specified module of the Occ Data component, if you try to upload a .csv with "scientific_name", "latitude", "longitude" columns (instead of the correct "scientific_name", "longitude", "latitude"), the log box error is 

 > ! ERROR : Please input just genus and species epithet in scientific name field in your file (e.g., "Canis lupus")(**).

Can this be changed to reflect the error is in the order of columns, or add to this message for user to check the order is long,lat, not lat, long?

**Comment by andrepazv** [comment]
done
