### ISSUE TITLE
Env Space crash after missing Step2 in Proc Envs

### ISSUE THREAD

**Issue by bjohnso005** [wallaceEcoMod/wallace#338]
If you move on to Env Space component before completing Step 2 in Process Envs (this is the step to mask predictor rasters by background extent and sample background points) Wallace crashes.
Warning: Error in rep: invalid 'times' argument
  2: shiny::runApp
  1: run_wallace

If you forget Step 2 in Process Envs, skip Env Space, and move on to Partition Occs, Wallace gives error warning "Before partitioning occurrences, mask your environmental variables by your background extent." instead of crashing. Env Space should give similar warning.

**Comment by andrepazv** [comment]
Fixed
