### ISSUE TITLE
Menu does not disappear

### ISSUE THREAD

**Issue by Pgalante** [wallaceEcoMod/wallace#346]
multiSp branch: In Env Data component/WorldClim Bioclims module, selecting bioclim variables button will not minimize after clicked

**Comment by andrepazv** [comment]
Well I got it to close but it is annoying and this was not a problem before. Assigning Gonzalo because this happened along with some of the new GUI changes

**Comment by gepinillab** [comment]
Can someone send me a screenshoot about this issue? I am not able to reproduce it, and everything works fine on my machine. Is there an error in the R console?

**Comment by Pgalante** [comment]
![wallaceMenu](https://user-images.githubusercontent.com/15325314/114460417-9701ed00-9baf-11eb-8985-46dff0b0c7d5.gif)

**Comment by gepinillab** [comment]
Is there an error in the R console?

**Comment by gepinillab** [comment]
@Pgalante a big favor. Can you check if this problem also happens when using Chrome? If no, this means that pickerInputs do not work for all browsers.

**Comment by Pgalante** [comment]
I don't have chrome, unfortunately.

**Comment by gepinillab** [comment]
Is there an error in the R console? Also, can you let me know which version of shinyWidgets is installed on your machine?

**Comment by andrepazv** [comment]
I tested in chrome and same issue with shinyWidgets 0.5.0

**Comment by gepinillab** [comment]
Thanks!

Please, Can you update to shinyWidgets 0.6.0 and see if the issue happens again?

**Comment by gepinillab** [comment]
https://cran.r-project.org/web/packages/shinyWidgets/news/news.html

It looks like the was a problem with pickerInputs related to a new version of Shiny. Whenever you have time, please install the latest version of shiny and shinyWidgets and let me know if the issue persits.

Thanks!

**Comment by Pgalante** [comment]
the shinyWidgets update solves it! Thanks, Gonzalo.

**Comment by gepinillab** [comment]
Excellent! 

I will specify the version of the package in the DESCRIPTION file.

Pete, thanks for letting us know!
