### ISSUE TITLE
Not able to partition occs

### ISSUE THREAD

**Issue by Pgalante** [wallaceEcoMod/wallace#347]
multiSp branch: In Part Occs component, neither module allows for partitioning occurrences. Cannot move past this component.

**Comment by andrepazv** [comment]
@Pgalante can you give us more info? It works fine on my end

**Comment by gepinillab** [comment]
I was not able to reproduce this issue. Everything is working fine on my machine.
@Pgalante Which ENMeval version do you have installed on your machine?

**Comment by andrepazv** [comment]
It was an old ENMeval version closing this one :D
