### ISSUE TITLE
Error on "Load Env Data" 

### ISSUE THREAD

**Issue by vijaybarve** [wallaceEcoMod/wallace#367]
````trying URL 'https://biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/bio_10m_bil.zip'
Warning in utils::download.file(url = aurl, destfile = fn, quiet = FALSE,  :
  InternetOpenUrl failed: 'A connection with the server could not be established'
Warning: Error in utils::download.file: cannot open URL 'https://biogeo.ucdavis.edu/data/climate/worldclim/1_4/grid/cur/bio_10m_bil.zip'`````

**Comment by hannahlowens** [comment]
Hi Gonzalo,
It seems the user-specified module for environmental data is working fine on Macs, but some folks with Windows machines hit an error after the models are generated. The GUI grays out and this is the output they get in RStudio:

```R
ENMevaluate completed in 5 minutes 42.9 seconds.
Warning: Error in Math.data.frame: non-numeric variable(s) in data frame: cbi.train
  2: shiny::runApp
  1: run_wallace
```

Any suggestions?

**Comment by hannahlowens** [comment]
> Hi Gonzalo, It seems the user-specified module for environmental data is working fine on Macs, but some folks with Windows machines hit an error after the models are generated. The GUI grays out and this is the output they get in RStudio:
> 
> ```r
> ENMevaluate completed in 5 minutes 42.9 seconds.
> Warning: Error in Math.data.frame: non-numeric variable(s) in data frame: cbi.train
>   2: shiny::runApp
>   1: run_wallace
> ```
> 
> Any suggestions?

In case anyone else has this problem, it can be fixed by updated R and then reinstalling Wallace.

**Comment by hannahlowens** [comment]
> 



> Hi Gonzalo, It seems the user-specified module for environmental data is working fine on Macs, but some folks with Windows machines hit an error after the models are generated. The GUI grays out and this is the output they get in RStudio:
> 
> ```r
> ENMevaluate completed in 5 minutes 42.9 seconds.
> Warning: Error in Math.data.frame: non-numeric variable(s) in data frame: cbi.train
>   2: shiny::runApp
>   1: run_wallace
> ```
> 
> Any suggestions?

In case anyone else runs into this second problem--it can be fixed by updating to the latest version of R and reinstalling Wallace.

**Comment by gepinillab** [comment]
Thanks @hannahlowens for posting the solution.

**Comment by sofia10h** [comment]
Hello everyone, 

I uploaded a raster from Soilgrids to wallace, but when I run the model in wallace using Maxent, I get the following warning and the screen freeze: 

50%Warning: Error in [: (subscript) logical subscript too long
  2: shiny::runApp
  1: run_wallace

Im wondering if someone can help me to solve this issue. Thank you!
