### ISSUE TITLE
Error in [: (subscript) logical subscript too long

### ISSUE THREAD

**Issue by sofia10h** [wallaceEcoMod/wallace#368]
Hello everyone, 

I uploaded a raster from Soilgrids to wallace, but when I run the model in wallace using Maxent, I get the following warning and the screen freeze: 

50%Warning: Error in [: (subscript) logical subscript too long
  2: shiny::runApp
  1: run_wallace

Im wondering if someone can help me to solve this issue. Thank you!

_Originally posted by @sofia10h in https://github.com/wallaceEcoMod/wallace/issues/367#issuecomment-1095549638_

**Comment by gepinillab** [comment]
Dear @sofia10h,

I am sorry to reply so late to this issue. I lost it in my e-mail inbox.

Did you were able to fix it? I think the issue could be related to the resolution of your rasters (250 m). R has some problems handling big raster in the memory RAM, which could be a potential reason for this problem.

Best,
Gonzalo
