### ISSUE TITLE
Cannot transfer to new time

### ISSUE THREAD

**Issue by antopg** [wallaceEcoMod/wallace#387]
Hi, I am new using wallace, everything works fine until a try to transfer to new time, the screen dims and the following lines appears on R Studio:

ENMevaluate completed in 0 minutes 12.6 seconds.
Warning: Error in if: argument is of length zero
  2: shiny::runApp
  1: run_wallace

I download Wallace V2.0 and the same error occurs.
Any solution to this? I need to deliver this on Monday, and I am stuck 😢 

Best regards,

Antonio

![image](https://user-images.githubusercontent.com/91863972/203920452-747fb3fb-af73-46e8-8fc8-e38d1d2c4e55.png)
![image](https://user-images.githubusercontent.com/91863972/203920506-3990fff2-56d6-4ff6-b3ee-c4b70dab9284.png)
![image](https://user-images.githubusercontent.com/91863972/203920906-fb91baa4-0dcf-4de8-8e9a-31a827ec3c6c.png)

**Comment by gepinillab** [comment]
Hi @antopg,

1a. Please install v1 from GitHub using the following code:
remotes::install_github("wallaceecomod/wallace@v1.1.3")

1b. Or please be sure to have the last version of v2 installed:
remotes::install_github("wallaceecomod/wallace")

2. Also, update to the latest versions of raster and terra packages available on CRAN.

I double-checked both versions, and they are working fine. If the issue persists, remember that you can use your own rasters in the TRANSFER component in v2. So, you just need to find the rasters in other sources outside **wallace**.

Best,
Gonzalo

**Comment by antopg** [comment]
I did 1a and 2, now I got two errors.

![image](https://user-images.githubusercontent.com/91863972/204118154-106c015d-397a-4717-b2e1-43fb930e908f.png)

**Comment by gjknowlton** [comment]
Running into the same issue described above. Also updated Wallace, Terra, & Raster packages. 

Trying to project out to future timeframe and also getting the error:
! ERROR : The polygon has not been drawn and finished. Please use the draw toolbar on the left-hand of the map to complete the polygon.

Then getting the grayed-out screen and unresponsive shiny app.

**Comment by gepinillab** [comment]
Hi again,

I am sorry for the late reply. I was offline last week.

Antonio (@antopg): Checking the first message, I noticed that you did not choose an RCP in the screenshot. This issue generates an error message at that moment. The second error occurred in the model component, not the transfer. I am unsure about the issue, but I hope you can use V2 instead. If the problem persists for V2, I will need more information about the input data you are using. We are doing a lot of testing, which is working fine for us! Keep in mind that v2 will be available on CRAN in a couple of weeks, so we are prioritizing bug fixes in that version.

Garrett (@gjknowlton): I will need all the error messages in the R/Rstudio console to figure out/confirm that you are having the same issue.

Best,
Gonzalo

**Comment by gepinillab** [comment]
Hi again,

There is a post related to this issue in [Google Groups](https://groups.google.com/g/wallaceEcoMod/c/ImsVKNjvTEo). The error message reported there allows us to identify and fix the error. Please let us know if your issue was not fixed in wallace v2.

Best,
Gonzalo
