### ISSUE TITLE
Inability to input user specific variables for "transfer to new time"

### ISSUE THREAD

**Issue by hart2** [wallaceEcoMod/wallace#393]
I'm running some models on seabirds and wanted to incorporate bio-oracle variables for 2050 rcp4.5 and rcp8.5. If I remember correctly I could have user specific future variables in a previous iteration of Wallace, but now I can only choose from ecoClimate for variables. Even if I wanted to choose ecoClimate, it won't let me utilize this option since I incorporated the surface present bio-oracle data. Is there a way to get around this and utilize the bio-oracle climatic data? Are they any plans to add this function to Wallace?

**Comment by gepinillab** [comment]
Hi @hart2,

I am surprised about this issue. I already have used bio-oracle variables in v2 without problems. The option of user-specified transfer variables is new in v2. You can upload them in the "Transfer to User Environments." Remember that you should name the raster using the same file names of the rasters uploaded in the "Component: Obtain Environmental Data.". Also, keep in mind that they should be the same number.

To help you more, it will need to know any error message you get in the Log Window on Wallace and the R console. Also, Wallace is crashing when uploading your user transfer rasters.

Best,
Gonzalo

**Comment by hart2** [comment]
Hi @gepinillab, 

I have restarted computer/ redownloaded R. There was an error with my computer. Thank you for your help and for all that Wallace provides!
