### ISSUE TITLE
Model Transfer with option for user's data

### ISSUE THREAD

**Issue by dpoursanidis** [wallaceEcoMod/wallace#419]
Hi team

While options for terrestrial datasets to be auto-used in "Model Transfer", no option for user's data to be used.
Example is the [BioOracle](https://bio-oracle.org/) database where is for the marine realm. The have now the ver 3 with lots of new [SSPs by IPCC](https://bio-oracle.org/downloads-to-email.php).
Good be great if at the GUI a user's dataset option could be added.
For now i take the code and add lines for my data

Best
D.

**Comment by gepinillab** [comment]
Hi Dimitris,

Since the release of Wallace v2, a new module can upload user-specified environmental data to the transfer component ("Transfer to User Environments"). This should be the option to upload the newest Biooracle database.

Please let me know if you have any questions.

Best,
Gonzalo

**Comment by dpoursanidis** [comment]
You are right! That slips from my attention!!
Thanks
