### ISSUE TITLE
Error in Retrieving Future Bioclim Data

### ISSUE THREAD

**Issue by ume722** [wallaceEcoMod/wallace#422]
Hello all,

I am currently using Wallace to project niche suitability for a species of primate to future timelines under different global circulation and socioeconomic scenarios. However, for the last two GCM and RCP pathways that I've tried, the projection and the entire Wallace session fails, and I get the following error in R:

Warning: Error in utils::download.file: cannot open URL 'https://biogeo.ucdavis.edu/data/climate/cmip5/2_5m/cc45bi50.zip'.

Does anyone know how to circumvent this issue, or whether the site itself is down? I am currently using v2.1.2, which to my understanding is the latest version, so perhaps extracting future bioclim rasters from this database is not yet set up on this version? Please let me know if you can!

Evan Miller

**Comment by bjohnso005** [comment]
This will be fixed in v2.2.0.

**Comment by ume722** [comment]
Thanks for letting me know! Do you have any approximation as to when v2.2.0 will be released?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Bethany A. Johnson ***@***.***>
Sent: Thursday, June 20, 2024 2:50:33 PM
To: wallaceEcoMod/wallace ***@***.***>
Cc: Evan Miller ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [wallaceEcoMod/wallace] Error in Retrieving Future Bioclim Data (Issue #422)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



This will be fixed in v2.2.0.

**Comment by bjohnso005** [comment]
Wallace v2.2.0 will implement the next version of `ENMeval`. Once ENMeval v2.0.5 makes it on CRAN, we will quickly follow.
But you can install both via github until then:
devtools::install_github("https://github.com/jamiemkass/ENMeval/tree/v205_draft")
devtools::install_github("https://github.com/wallaceEcoMod/wallace/tree/dev")

**Comment by ume722** [comment]
Awesome, thank you so much for your help!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Bethany A. Johnson ***@***.***>
Sent: Thursday, June 20, 2024 4:11:09 PM
To: wallaceEcoMod/wallace ***@***.***>
Cc: Evan Miller ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [wallaceEcoMod/wallace] Error in Retrieving Future Bioclim Data (Issue #422)

  **EXTERNAL EMAIL**
  This email originated outside of The University of Texas at San Antonio.
  Please exercise caution when clicking on links or opening attachments.



Wallace v2.2.0 will implement the next version of ENMeval. Once ENMeval v2.0.5 makes it on CRAN, we will quickly follow.
But you can install both via github until then:
devtools::install_github("https://github.com/jamiemkass/ENMeval/tree/v205_draft")
devtools::install_github("https://github.com/wallaceEcoMod/wallace/tree/dev")

**Comment by bjohnso005** [comment]
Closed with release of 2.1.3  
#436
