### ISSUE TITLE
Inconsistent "Module" nomenclature used for Partition Occurrence Component

### ISSUE THREAD

**Issue by mlammens** [wallaceEcoMod/wallace#77]
It doesn't look like we're using "Module" in the same way in this Component as in the other Components. It seems like we want "Non-spatial ..." and "Spatial Partition" to be called the "Module"s, and the different types of partitioning to be called the "Options".

**Comment by ndimhypervol** [comment]
Yes, we are calling "Spatial Partition" and "Non-spatial Partition" the modules, and the partitioning types something akin to options. Is this the inconsistent thing, or is this how you think it should be? This layout is similar to how comp 4 works.

**Comment by mlammens** [comment]
Looking at the GUI, right below 'Partition Occurrence Data' is the text 'Options Available:' with buttons for 'Non-Spatial Partition' and 'Spatial Partition'. This should be 'Modules Available'.
Then below in the actual module, the section we want to call 'Options' is currently labeled as 'Modules'.

**Comment by ndimhypervol** [comment]
Roger that. Another good catch!
