### ISSUE TITLE
tooltip: 7 Visualize - Map Prediction - Prediction output

### ISSUE THREAD

**Issue by mlammens** [wallaceEcoMod/wallace#78]

**Comment by mlammens** [comment]
Text:
*raw* - sum of pixel values is 1.
*logistic* - each raw pixel value converted to a value between 0 and 1, indicative of the relative rate of occurrence of the species in that pixel. Default conversion assumes species prevalence is 0.5.

**Comment by ndimhypervol** [comment]
Altered a little bit to emphasize that logistic is sort of a "probability of presence" with the assumption of prevalence = 0.5.
