### ISSUE TITLE
Projection with BIOCLIM model crashed Shiny App

### ISSUE THREAD

**Issue by mlammens** [wallaceEcoMod/wallace#80]
I selected the first of each of the projection to a new time options, and shiny immediately crashed. Here's everything that was in my console:

Warning in .cmip5(..., download = download, path = path) :
  this combination of rcp and model is not available
Warning: Error in <Anonymous>: unable to find an inherited method for function ‘crop’ for signature ‘"NULL"’
Stack trace (innermost first):
    71: <Anonymous>
    70: crop
    69: eval [modules/mods_comp8.R#73]
    68: eval
    67: withProgress
    66: comp8_pjTime [modules/mods_comp8.R#72]
    65: observeEventHandler [/Users/mlammens/Dropbox/Projects/Wallace/wallace/server.R#769]
     1: shiny::runApp

**Comment by ndimhypervol** [comment]
Great catch! Meant to add this catch but forgot a while back. Borrowed code from the `dismo` getData() function to make sure unavailable gcm / rcp combos don't make Wallace crash.
