### ISSUE TITLE
rJava problems

### ISSUE THREAD

**Issue by mlammens** [wallaceEcoMod/wallace#87]
@ndimhypervol what are the plans around potentially using maxnet to avoid using Java? I'm finding that for both myself and my students, getting rJava to work easily is a real challenge.

**Comment by wallaceEcoMod** [comment]
@mlammens I have been working on a maxnet extension for `ENMeval`, but there are still a few issues to resolve. It mostly works fine. The one thing that does not work is how `rJava` plays with `parallel` -- it seems that the new R version, or something, is making it impossible to run maxent() in a parallel process, but maxnet() works fine.

**Comment by mlammens** [comment]
OK. In the mean time, rJava apparently doesn't work "out of the box" on Mac OS 10.10 (and possibly on Linux machines) without some command-line trickery. Here's a link to a SO message that finally helped me. http://stackoverflow.com/questions/30738974/rjava-load-error-in-rstudio-r-after-upgrading-to-osx-yosemite

**Comment by wallaceEcoMod** [comment]
Just added this link to the README for Mac users. Thx Matt!
