### ISSUE TITLE
Raster file download is failing

### ISSUE THREAD

**Issue by mlammens** [wallaceEcoMod/wallace#88]
Here's the error message I see in the R console

Warning: Error in writeRaster: could not find function "writeRaster"
Stack trace (innermost first):
    51: download$func [/Library/Frameworks/R.framework/Versions/3.4/Resources/library/wallace/shiny/server.R#755]
     2: shiny::runApp
     1: run_wallace
Error : could not find function "writeRaster"

**Comment by mlammens** [comment]
@ndimhypervol Quick follow up on this bug. If I `library(raster)` then start Wallace, the download seems to work. Seems like raster isn't being loaded when wallace is loaded?

**Comment by wallaceEcoMod** [comment]
Just put an explicit reference to writeRaster(). It now reads raster::writeRaster(). Should have been that way before. Thanks for catching that! Will update with new version soon.
